_wandb:
    value:
        cli_version: 0.21.0
        e:
            5mdblqkd2csjl4ly6s63q30hxq18tsxm:
                args:
                    - --config
                    - /mnt/lustre/koa/scratch/jans26/streamflow/KAHAWAI-Project/models/water_stage_classification/config_DAR_comb_046.yaml
                codePath: models/water_stage_classification/train2.py
                codePathLocal: train2.py
                cpu_count: 48
                cpu_count_logical: 48
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "101219061760"
                        used: "10803847168"
                email: jans26@hawaii.edu
                executable: /home/jans26/.conda/envs/streamflow-env/bin/python
                git:
                    commit: 6dd012f01ad168ea2802c9c743e13b7d0efd5155
                    remote: https://github.com/jamasc/KAHAWAI-Project.git
                gpu: Tesla V100-SXM2-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100-SXM2-32GB
                      uuid: GPU-6aee7a3c-b18d-d64d-e338-f6411be49cf5
                host: gn-16-14-00
                memory:
                    total: "202438127616"
                os: Linux-5.14.0-611.34.1.el9_7.x86_64-x86_64-with-glibc2.34
                program: /mnt/lustre/koa/scratch/jans26/streamflow/KAHAWAI-Project/models/water_stage_classification/train2.py
                python: CPython 3.13.5
                root: /mnt/lustre/koa/scratch/jans26/streamflow/KAHAWAI-Project/models/water_stage_classification
                slurm:
                    cluster_name: mana
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    immediate: "120"
                    job_account: uh
                    job_cpus_per_node: "8"
                    job_end_time: "1773036774"
                    job_gid: "7489"
                    job_gpus: "5"
                    job_id: "11443231"
                    job_name: water_stage
                    job_nodelist: gn-16-14-00
                    job_num_nodes: "1"
                    job_partition: gpu
                    job_qos: normal
                    job_start_time: "1772863974"
                    job_uid: "7489"
                    job_user: jans26
                    jobid: "11443231"
                    localid: "0"
                    mem_per_node: "32000"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gn-16-14-00
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /mnt/lustre/koa/scratch/jans26/streamflow/KAHAWAI-Project/models/water_stage_classification
                    submit_host: login-0101
                    task_pid: "213018"
                    tasks_per_node: "1"
                    topology_addr: gn-16-14-00
                    topology_addr_pattern: node
                    tres_per_task: cpu=8
                startedAt: "2026-03-07T06:13:14.027260Z"
                writerId: 5mdblqkd2csjl4ly6s63q30hxq18tsxm
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.13.5
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 100
learning_rate:
    value: 0.001
