# project
wandb_project: 'pukele_classification'
wandb_name: 'run 11/11'
data_inventory_path: '/home/jans26/koa_scratch/streamflow/data/pukele_datasheet.xlsx'
embedding_path: '/home/jans26/koa_scratch/streamflow/features/pukele_embeddings.pt'
model_save_path: '/home/jans26/koa_scratch/streamflow/models/pukele_classifier_head.pth'

# training parameters
learning_rate: 0.01
epochs: 100
batch_size: 32
train_split: 0.7
val_split: 0.2
random_seed: 42

